### ISSUE TITLE
Where can we find the link to yesterday's jupyter notebook?

### ISSUE THREAD

**Issue by HaithamMaya** [PyDataAnnArbor/Meetup#9]

**Comment by adithyasailesh** [comment]
PyData Ann Arbor: Amy Hemmeter | Summarization of News Articles Using TextRank
https://github.com/amyhemmeter/textrank-summarization-pydata-talk

**Comment by quasiben** [comment]
Thanks @HaithamMaya for the question and @adithyasailesh for the answer!
